-- Expanded Manager discovery seed.
-- Data-only, idempotent, no schema changes.

insert into public.manager_sources (
  name,
  source_kind,
  platform,
  url,
  handle,
  location_city,
  location_state,
  active,
  check_frequency_hours,
  check_reliability,
  recommended_demo,
  recommended_demo_reason,
  notes
)
values
  (
    'Indy Arts Council Opportunities',
    'event_brand',
    'website',
    'https://indyarts.org/opportunities/',
    null,
    'Indianapolis',
    'IN',
    true,
    24,
    'partial',
    'Open Format / Arts / Community',
    'Use the closest event-specific demo; this source publishes performing calls, DJ curation requests, artist opportunities, and local paid activations.',
    'High-value local opportunity board. Prefer current performing/music/DJ calls and ignore unrelated visual-art, grant, or volunteer listings.'
  ),

  (
    'CHREECE',
    'event_brand',
    'website',
    'https://www.chreeceaf.com/',
    null,
    'Indianapolis',
    'IN',
    true,
    24,
    'partial',
    'Hip-Hop / Open Format',
    'CHREECE explicitly programs DJs and producers in its Indianapolis hip-hop festival ecosystem.',
    'Watch for future artist/DJ submissions, showcase calls, after-parties, partner events, and venue relationships.'
  ),



  (
    'IU Indianapolis Weeks of Welcome',
    'event_brand',
    'website',
    'https://studentaffairs.indianapolis.iu.edu/get-involved/wow/index.html',
    null,
    'Indianapolis',
    'IN',
    true,
    48,
    'partial',
    'Clean Open Format / Campus',
    'The recurring campus program includes large student social events and has used live DJs.',
    'Watch annual Weeks of Welcome, Light Up the Night, student programming, vendor/event-partner signals, and campus entertainment contacts.'
  ),
  (
    '500 Festival',
    'event_brand',
    'website',
    'https://500festival.com/',
    null,
    'Indianapolis',
    'IN',
    true,
    48,
    'partial',
    'Clean Open Format / Corporate / Community',
    'Large public-facing Indianapolis event portfolio favors polished, sponsor-safe, high-energy programming.',
    'Watch 2027 event announcements, entertainment programming, activations, vendor opportunities, partner events, and recurring May programming.'
  ),
  (
    'IndyFringe',
    'event_brand',
    'website',
    'https://indyfringe.org/festival/',
    null,
    'Indianapolis',
    'IN',
    true,
    72,
    'partial',
    'Open Format / Arts / Festival',
    'Festival and arts programming can create performance, event, and cross-disciplinary opportunities.',
    'Watch 2027 artist applications, festival events, parties, programming calls, and partner venues.'
  ),
  (
    'The Patron Saint',
    'venue',
    'website',
    'https://patronsaintindy.com/',
    null,
    'Indianapolis',
    'IN',
    true,
    24,
    'partial',
    'House / Ghetto Tech / Juke',
    'The venue is DJ-driven nightlife and is a direct fit for house, ghetto tech, juke, dance, and club-forward material.',
    'Watch upcoming shows, guest-DJ programming, recurring promoters, support slots, and collaborators.'
  ),
  (
    'Biltwell Event Center',
    'venue',
    'website',
    'https://www.biltwelleventcenter.com/',
    null,
    'Indianapolis',
    'IN',
    true,
    72,
    'partial',
    'Clean Open Format / Wedding / Corporate',
    'Large weddings, social events, corporate events, and nonprofit events fit polished open-format programming.',
    'Reference source for event organizers, vendor showcases, corporate clients, and recurring entertainment relationships.'
  ),
  (
    'Indiana Roof Ballroom',
    'venue',
    'website',
    'https://www.indianaroof.com/',
    null,
    'Indianapolis',
    'IN',
    true,
    72,
    'partial',
    'Clean Wedding / Corporate',
    'Premium weddings, galas, corporate events, and social gatherings favor clean, professional open-format programming.',
    'Watch public events, big-band/social programming, gala organizers, corporate clients, and entertainment/vendor signals.'
  ),
  (
    'Tinker House Events',
    'venue',
    'website',
    'https://www.tinkerhouseevents.com/',
    null,
    'Indianapolis',
    'IN',
    true,
    72,
    'partial',
    'Lounge / Open Format / Corporate',
    'Weddings, private parties, corporate events, and a modern industrial setting fit lounge-to-dance open-format programming.',
    'Reference source for planners, corporate gatherings, social events, and vendor/event relationships.'
  ),
  (
    'DJ GNO',
    'dj',
    'website',
    'https://gnouniverse.com/',
    null,
    'Indianapolis',
    'IN',
    true,
    72,
    'partial',
    null,
    null,
    'Network-reference source. Mine sporting events, corporate activations, festivals, weddings, venues, brands, and recurring collaborators; do not treat booking inquiries as opportunities by themselves.'
  )
on conflict (url) do update
set
  name = excluded.name,
  source_kind = excluded.source_kind,
  platform = excluded.platform,
  handle = excluded.handle,
  location_city = excluded.location_city,
  location_state = excluded.location_state,
  active = excluded.active,
  check_frequency_hours = excluded.check_frequency_hours,
  check_reliability = excluded.check_reliability,
  recommended_demo = excluded.recommended_demo,
  recommended_demo_reason = excluded.recommended_demo_reason,
  notes = excluded.notes;
